#!/bin/sh

umask 077
set -e

. /usr/lib/cfmaint/common.sh

echo -n "Mounting /config rw "
mount -o remount,rw,sync,dirsync /config
cd /config
echo "done"

echo -n "Creating new archive "
idx=`get_last_valid_idx`
if [ -z "$idx" ]; then
	idx=1
else
	let 'idx=idx+1'
fi
echo -n "[idx=$idx] "

t="$config_prefix.$idx"
f="$config_prefix.tmp"
tar cf - -C / etc | gzip -c9 > "$f"
md5sum < "$f" > "$f.md5"

mv "$f.md5" "$t.md5"
mv "$f" "$t"
echo "done"

echo -n "Mounting /config ro "
mount -o remount,ro /config
echo "done"
