#!/bin/sh

# dont exit on errors
set +e
umask 077

# determine which step are we in
part2_type=$(fdisk -l $__system_device | grep "^${__system_device}2" | awk '{print $5}')

if [ -z "$part2_type" ]; then # STEP 2
	exit
fi

# STEP 1
echo "Configuration upgrade begins"
. /usr/lib/cfmaint/common.sh

# create the partition
tp="${__system_device}1"
mke2fs "$tp" > /dev/null 2>&1
mount -nt ext2 "$tp" $config_part
chmod 700 $config_part

# create temp working area
mount none -nt tmpfs -o size=16M,mode=700 /mnt
conf=$(get_fresh_and_valid)
mkdir /mnt/etc
if [ -n "$conf" ] && mount -nt minix "$conf" /mnt/etc > /dev/null 2>&1 ; then
	# edit fstab
	sed -i'' -e '/^\/dev\/ram0[[:space:]]\+\/etc/d' /mnt/etc/fstab
	echo -e "$tp\t/config\t\text2\tro\t\t\t0\t0" >> /mnt/etc/fstab

	# create archive
	tar cf - -C /mnt etc | gzip -c9 > /mnt/$config_prefix.1
	umount /mnt/etc > /dev/null 2>&1

	cd $config_part
	cp /mnt/$config_prefix.1 .
	md5sum < $config_prefix.1 > $config_prefix.1.md5
	cd /
fi
rm -rf /mnt/etc
umount /mnt

umount $config_part

part3_st=$(fdisk -l $__system_device | grep "^${__system_device}3" | awk '{print $2}')
part1_t_end=$(expr $part3_st - 1)

echo -e "d\n2\nd\n1\nn\np\n1\n1\n$part1_t_end\nw" | fdisk "${__system_device}" > /dev/null 2>&1

sync

echo "*"
echo "* Upgrade notice"
echo "*"
echo "* The configuration partition has been upgraded. To use the full capacity of it"
echo "* issue the following commands after the system has booted up:"
echo " # umount /config"
echo " # mke2fs $tp"
echo " # mount /config"
echo " # savedata"
echo ""
echo "* (Sleeping for 20 seconds...)"
sleep 20
reboot -f
